const products = [
  {
    _id: 1,
    name: "Modern Leather Sofa",
    description: "This is a description of the product",
    brand: "Leather",
    category: "Sofa",
    price: 12500,
    countInStock: 5,
    rating: 2.5,
    numReviews: 10,
    image: "../../src/assets/Images/Sofa.jpg",
  },
  {
    _id: 2,
    name: "Wooden Chair",
    description: "This is a description of the product",
    brand: "Wooden",
    category: "Chair",
    price: 5000,
    countInStock: 10,
    rating: 3.5,
    numReviews: 3,
    image: "../../src/assets/Images/Chair.jpg",
  },
  {
    _id: 3,
    name: "IMac",
    description: "This is a description of the product",
    brand: "Wooden",
    category: "Laptop",
    price: 75000,
    countInStock: 15,
    rating: 4.0,
    numReviews: 7,
    image: "../../src/assets/Images/IMac.jpg",
  },
  {
    _id: 4,
    name: "Watch",
    description: "This is a description of the product",
    brand: "Leather",
    category: "Watch",
    price: 6000,
    countInStock: 9,
    rating: 5.0,
    numReviews: 1,
    image: "../../src/assets/Images/Watch.jpg",
  },
  {
    _id: 5,
    name: "T-shirt",
    description: "This is a description of the product",
    brand: "Clothes",
    category: "T-shirt",
    price: 1000,
    countInStock: 20,
    rating: 2.5,
    numReviews: 2,
    image: "../../src/assets/Images/T-shirt.jpg",
  },
  {
    _id: 6,
    name: "Pants",
    description: "This is a description of the product",
    brand: "Premium",
    category: "Pants",
    price: 1500,
    countInStock: 0,
    rating: 0,
    numReviews: 3,
    image: "../../src/assets/Images/Pants.jpg",
  },
  {
    _id: 7,
    name: "IPhone",
    description: "This is a description of the product",
    brand: "Apple",
    category: "Mobiles",
    price: 55000,
    countInStock: 22,
    rating: 4.2,
    numReviews: 3,
    image: "../../src/assets/Images/IPhone.jpg",
  },
  {
    _id: 8,
    name: "Speaker",
    description: "This is a description of the product",
    brand: "Premium",
    category: "Speaker",
    price: 3000,
    countInStock: 100,
    rating: 3.8,
    numReviews: 20,
    image: "../../src/assets/Images/Speaker.jpg",
  },
  {
    _id: 9,
    name: "Table",
    description: "This is a description of the product",
    brand: "Wooden",
    category: "Furniture",
    price: 12500,
    countInStock: 5,
    rating: 4.5,
    numReviews: 10,
    image: "../../src/assets/Images/Table.jpg",
  },
  {
    _id: 10,
    name: "Shoes",
    description: "This is a description of the product",
    brand: "Leather",
    category: "Shoes",
    price: 12500,
    countInStock: 4,
    rating: 2.5,
    numReviews: 2,
    image: "../../src/assets/Images/Shoes.jpg",
  },
];

export default products;
